# Generated by Django 4.1.2 on 2022-12-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_alter_article_pub_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название цветка')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Цена')),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
