# Generated by Django 4.1.2 on 2023-01-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_flower_delete_article_delete_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flower',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
