# Generated by Django 4.1.2 on 2023-01-01 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_flower_description_alter_flower_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='photo',
        ),
    ]
