# Generated by Django 4.1.2 on 2023-01-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_flower_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flower',
            options={'verbose_name': 'Цветок', 'verbose_name_plural': 'Цветки'},
        ),
        migrations.AlterField(
            model_name='flower',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
