# Generated by Django 4.1.2 on 2023-01-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_alter_flower_options_alter_flower_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='photo',
            field=models.ImageField(blank=True, upload_to='flowerImage'),
        ),
    ]
